### ISSUE TITLE
[Web] 経由地点を求める

### ISSUE THREAD

**Issue by kobayang** [enpit-ateam/prunner#4]
- 目的
  走りたい距離の半分の場所にあるスポットを求め、そこを往復することで目的の距離のルートを提案するため
- 実装
  経由地点を求める関数を作成する.
  Google Mapを開いた際、コンビニと検索するとGoogle Mapに表示されている範囲内のコンビニが優先して結果に出るので、それを応用すればFoursquareのような他のサイトを使わず実装できる・・・？
- ToDo
- [x] スポットの定義を決める -> https://developers.google.com/maps/documentation/javascript/places?hl=ja#radar_search_requests で帰ってきたものの中で一番遠いものを選ぶ
- [ ] ~~上で決めたスポットから距離で絞りこめるようにする~~
- [x] https://developers.google.com/maps/documentation/javascript/places?hl=ja#radar_search_requests を使えるようにする
- [x] 上で求めたスポットの中で一番遠いものを使うようにする
- 使用できそうなAPI
  - Foursquare (http://qiita.com/koogawa/items/df92ec1c7eb750312b77 に距離で検索できる機能が書いてある)
  - Google Api （https://developers.google.com/maps/documentation/javascript/places?hl=ja#radar_search_requests ここらへんの機能を使えばよさそう）
  - etc...

**Comment by rerost** [comment]
Google Map APIにスポットを距離から検索する機能があったので、そちらを使おうと思います

**Comment by rerost** [comment]
検索範囲内の中で現在位置から一番遠い距離を目的のスポットとします

**Comment by a1a1a2a4** [comment]
レーダー検索リクエストを実行する

**Comment by rerost** [comment]
調べてほしいこと
- [ ] 指定した位置（筑波大学）にピンを落とす方法
- [ ] Google Map API で距離を求める方法

**Comment by a1a1a2a4** [comment]
masterにpushしました。
